#!/bin/bash
file 0-isupper.o
file 0-memset.o
file 0-strcat.o
file 1-isdigit.o
file 1-memcpy.o
file 1-strncat.o
file 100-atoi.o
file 2-strchr.o
file 2-strlen.o
file 2-strncpy.o
file 3-islower.o
file 3-puts.o
file 3-strcmp.o
file 3-strspn.o
file 4-isalpha.o
file 4-strpbrk.o
file 5-strstr.o
file 6-abs.o
file 9-strcpy.o
file _putchar.o
